export const DEFAULT_CONFIG = {
  title: 'Flash Card Set',
  mode: 'words',
  wordsPerCard: 1,
  preserveLineBreaks: false,
  removePunctuation: false,
  separatePunctuation: false,
  transform: 'none',
  trimWhitespace: true,
  dedupeEmptyCards: true,
  printBacks: true,
  showBackOrder: true,
  page: {
    size: 'letter',
    orientation: 'portrait',
    margin: 24,
    gutter: 12,
    rows: 4,
    cols: 3,
    cutMarkLength: 8,
    cutMarkInset: 4,
    cutMarkThickness: 0.4,
    cutMarkColor: '#C7C7C7',
    showPageTitle: true,
    pageTitleFontSize: 14,
  },
  card: {
    titleFontSize: 9,
    bodyFontSize: 22,
    bodyMinFontSize: 11,
    lineHeight: 1.2,
    padding: 10,
    borderColor: '#4A6FA5',
    borderWidth: 1,
    cornerRadius: 0,
    titleBandHeight: 16,
    titleColor: '#4A6FA5',
    titleTextColor: '#FFFFFF',
    bodyTextColor: '#111111',
    backgroundColor: '#FFFFFF',
    align: 'center',
    verticalAlign: 'middle',
  },
};